# Generated by Django 3.2.4 on 2021-08-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('via', models.IntegerField(choices=[[0, 'sector 1'], [1, 'sector 2'], [2, 'sector 3']])),
                ('imagen_via', models.ImageField(blank=True, null=True, upload_to='gallery')),
            ],
        ),
    ]
