# Generated by Django 3.1.7 on 2021-03-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('descripcion', models.TextField(max_length=500)),
                ('telefono', models.CharField(max_length=15)),
                ('imagen1', models.ImageField(upload_to='')),
                ('imagen2', models.ImageField(upload_to='')),
                ('imagen3', models.ImageField(upload_to='')),
                ('imagen4', models.ImageField(upload_to='')),
                ('imagen5', models.ImageField(upload_to='')),
            ],
        ),
    ]
