# Generated by Django 3.1.7 on 2021-05-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0005_auto_20210329_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='pub_date',
            new_name='fecha_publicacion',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='telefono',
            field=models.CharField(max_length=13),
        ),
    ]
