# Generated by Django 3.1.7 on 2021-05-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interes',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
