# Generated by Django 3.1.7 on 2021-06-10 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interes', '0003_auto_20210525_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imagenes',
        ),
    ]
