# Generated by Django 3.2.4 on 2021-06-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugerencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerencia',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
