# Generated by Django 3.1.7 on 2021-05-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=500)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('imagen5', models.ImageField(blank=True, null=True, upload_to='gallery')),
            ],
        ),
    ]
