# Generated by Django 3.1.7 on 2021-05-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actividades',
            new_name='Actividad',
        ),
    ]
