# Generated by Django 3.1.7 on 2021-05-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_auto_20210512_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
