# Generated by Django 3.1.7 on 2021-05-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_actividad_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='contacto',
            field=models.TextField(default=3113253000, max_length=20),
            preserve_default=False,
        ),
    ]
