# Generated by Django 3.1.7 on 2021-04-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='header',
            new_name='home',
        ),
    ]
