# Generated by Django 3.1.7 on 2021-04-22 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210419_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='home',
            new_name='header',
        ),
    ]
