# Generated by Django 3.1.7 on 2021-04-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210421_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='header',
            new_name='imagen_header',
        ),
    ]
