# Generated by Django 3.1.7 on 2021-05-14 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_auto_20210512_1353'),
        ('home', '0004_auto_20210422_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('imagen_url', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('actividad_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.actividad')),
            ],
        ),
    ]
