# Generated by Django 3.1.7 on 2021-05-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210514_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='imagen_paralax',
            field=models.ImageField(blank=True, null=True, upload_to='gallery'),
        ),
    ]
