# Generated by Django 3.1.7 on 2021-06-10 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interes', '0004_delete_imagenes'),
        ('home', '0009_auto_20210529_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='interes_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interes.interes'),
        ),
    ]
