# Generated by Django 3.1.7 on 2021-06-10 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
        ('home', '0010_imagenes_interes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenes',
            name='galeria_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='galeria.galeria'),
        ),
    ]
